-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 14:16:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RP_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RP_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RP_bd` DEFAULT CHARACTER SET utf8 ;
USE `RP_bd` ;

-- -----------------------------------------------------
-- Table `RP_bd`.`tb_plantacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_plantacao` (
  `id_plantacao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_plantacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_Planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_Planta` (
  `id_Planta` INT NOT NULL AUTO_INCREMENT,
  `tipo_ amostra` VARCHAR(45) NOT NULL,
  `dt_plantacao` DATE NOT NULL,
  `plantacao_id_plantacao` INT NOT NULL,
  PRIMARY KEY (`id_Planta`),
  INDEX `fk_tb_Planta_tb_plantacao_idx` (`plantacao_id_plantacao` ASC),
  CONSTRAINT `fk_tb_Planta_tb_plantacao`
    FOREIGN KEY (`plantacao_id_plantacao`)
    REFERENCES `RP_bd`.`tb_plantacao` (`id_plantacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_temperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_temperatura` (
  `id_temperatura` INT NOT NULL AUTO_INCREMENT,
  `temperatura` DOUBLE NOT NULL,
  `hora_amostra` DATETIME NOT NULL,
  PRIMARY KEY (`id_temperatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_umidade_solo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_umidade_solo` (
  `id_umidade_solo` INT NOT NULL AUTO_INCREMENT,
  `umidade` DOUBLE NOT NULL,
  `hora_amostra` DATETIME NOT NULL,
  PRIMARY KEY (`id_umidade_solo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_umidade_ar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_umidade_ar` (
  `id_umidade_ar` INT NOT NULL AUTO_INCREMENT,
  `umidade` DOUBLE NOT NULL,
  `hora_amostra` DATETIME NOT NULL,
  PRIMARY KEY (`id_umidade_ar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`media_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`media_dia` (
  `idmedia_dia` INT NOT NULL,
  PRIMARY KEY (`idmedia_dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_mudanca_climatica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_mudanca_climatica` (
  `id_atividades` INT NOT NULL AUTO_INCREMENT,
  `hora` DATETIME NOT NULL,
  `descricao_atividade` VARCHAR(45) NULL,
  `tb_temperatura_id_temperatura` INT NOT NULL,
  `tb_umidade_ar_id_umidade_ar` INT NOT NULL,
  `tb_umidade_solo_id_umidade_solo` INT NOT NULL,
  PRIMARY KEY (`id_atividades`),
  INDEX `fk_tb_mudanca_climatica_tb_temperatura1_idx` (`tb_temperatura_id_temperatura` ASC),
  INDEX `fk_tb_mudanca_climatica_tb_umidade_ar1_idx` (`tb_umidade_ar_id_umidade_ar` ASC),
  INDEX `fk_tb_mudanca_climatica_tb_umidade_solo1_idx` (`tb_umidade_solo_id_umidade_solo` ASC),
  CONSTRAINT `fk_tb_mudanca_climatica_tb_temperatura1`
    FOREIGN KEY (`tb_temperatura_id_temperatura`)
    REFERENCES `RP_bd`.`tb_temperatura` (`id_temperatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_mudanca_climatica_tb_umidade_ar1`
    FOREIGN KEY (`tb_umidade_ar_id_umidade_ar`)
    REFERENCES `RP_bd`.`tb_umidade_ar` (`id_umidade_ar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_mudanca_climatica_tb_umidade_solo1`
    FOREIGN KEY (`tb_umidade_solo_id_umidade_solo`)
    REFERENCES `RP_bd`.`tb_umidade_solo` (`id_umidade_solo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_consumo_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_consumo_diario` (
  `id_consumo_diario` INT NOT NULL AUTO_INCREMENT,
  `qt_agua` DOUBLE NOT NULL,
  `qt_energia` DOUBLE NOT NULL,
  `qt_luminosidade` DOUBLE NOT NULL,
  PRIMARY KEY (`id_consumo_diario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_energia_armazenada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_energia_armazenada` (
  `id_energia_armazenada` INT NOT NULL AUTO_INCREMENT,
  `qt_energia` DOUBLE NOT NULL,
  PRIMARY KEY (`id_energia_armazenada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_health`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_health` (
  `id_health` INT NOT NULL,
  PRIMARY KEY (`id_health`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_dados_key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_dados_key` (
  `Planta_id_Planta` INT NOT NULL,
  `umidade_solo_id_umidade_solo` INT NOT NULL,
  `umidade_ar_id_umidade_ar` INT NOT NULL,
  `temperatura_id_temperatura` INT NOT NULL,
  PRIMARY KEY (`Planta_id_Planta`, `umidade_solo_id_umidade_solo`, `umidade_ar_id_umidade_ar`, `temperatura_id_temperatura`),
  INDEX `fk_tb_Planta_has_tb_umidade_solo_tb_umidade_solo1_idx` (`umidade_solo_id_umidade_solo` ASC),
  INDEX `fk_tb_Planta_has_tb_umidade_solo_tb_Planta1_idx` (`Planta_id_Planta` ASC),
  INDEX `fk_tb_Planta_has_tb_umidade_solo_tb_umidade_ar1_idx` (`umidade_ar_id_umidade_ar` ASC),
  INDEX `fk_tb_Planta_has_tb_umidade_solo_tb_temperatura1_idx` (`temperatura_id_temperatura` ASC),
  CONSTRAINT `fk_tb_Planta_has_tb_umidade_solo_tb_Planta1`
    FOREIGN KEY (`Planta_id_Planta`)
    REFERENCES `RP_bd`.`tb_Planta` (`id_Planta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Planta_has_tb_umidade_solo_tb_umidade_solo1`
    FOREIGN KEY (`umidade_solo_id_umidade_solo`)
    REFERENCES `RP_bd`.`tb_umidade_solo` (`id_umidade_solo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Planta_has_tb_umidade_solo_tb_umidade_ar1`
    FOREIGN KEY (`umidade_ar_id_umidade_ar`)
    REFERENCES `RP_bd`.`tb_umidade_ar` (`id_umidade_ar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Planta_has_tb_umidade_solo_tb_temperatura1`
    FOREIGN KEY (`temperatura_id_temperatura`)
    REFERENCES `RP_bd`.`tb_temperatura` (`id_temperatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_atividade_solo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_atividade_solo` (
  `tb_umidade_solo_id_umidade_solo` INT NOT NULL,
  `tb_historico_atividades_id_atividades` INT NOT NULL,
  PRIMARY KEY (`tb_umidade_solo_id_umidade_solo`, `tb_historico_atividades_id_atividades`),
  INDEX `fk_tb_umidade_solo_has_tb_historico_atividades_tb_historico_idx` (`tb_historico_atividades_id_atividades` ASC),
  INDEX `fk_tb_umidade_solo_has_tb_historico_atividades_tb_umidade_s_idx` (`tb_umidade_solo_id_umidade_solo` ASC),
  CONSTRAINT `fk_tb_umidade_solo_has_tb_historico_atividades_tb_umidade_solo1`
    FOREIGN KEY (`tb_umidade_solo_id_umidade_solo`)
    REFERENCES `RP_bd`.`tb_umidade_solo` (`id_umidade_solo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_umidade_solo_has_tb_historico_atividades_tb_historico_a1`
    FOREIGN KEY (`tb_historico_atividades_id_atividades`)
    REFERENCES `RP_bd`.`tb_mudanca_climatica` (`id_atividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_atividade_ar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_atividade_ar` (
  `tb_historico_atividades_id_atividades` INT NOT NULL,
  `tb_umidade_ar_id_umidade_ar` INT NOT NULL,
  PRIMARY KEY (`tb_historico_atividades_id_atividades`, `tb_umidade_ar_id_umidade_ar`),
  INDEX `fk_tb_historico_atividades_has_tb_umidade_ar_tb_umidade_ar1_idx` (`tb_umidade_ar_id_umidade_ar` ASC),
  INDEX `fk_tb_historico_atividades_has_tb_umidade_ar_tb_historico_a_idx` (`tb_historico_atividades_id_atividades` ASC),
  CONSTRAINT `fk_tb_historico_atividades_has_tb_umidade_ar_tb_historico_ati1`
    FOREIGN KEY (`tb_historico_atividades_id_atividades`)
    REFERENCES `RP_bd`.`tb_mudanca_climatica` (`id_atividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_historico_atividades_has_tb_umidade_ar_tb_umidade_ar1`
    FOREIGN KEY (`tb_umidade_ar_id_umidade_ar`)
    REFERENCES `RP_bd`.`tb_umidade_ar` (`id_umidade_ar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_atividades_temperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_atividades_temperatura` (
  `tb_historico_atividades_id_atividades` INT NOT NULL,
  `tb_temperatura_id_temperatura` INT NOT NULL,
  PRIMARY KEY (`tb_historico_atividades_id_atividades`, `tb_temperatura_id_temperatura`),
  INDEX `fk_tb_historico_atividades_has_tb_historico_atividades_tb_h_idx1` (`tb_historico_atividades_id_atividades` ASC),
  INDEX `fk_tb_historico_atividades_has_tb_historico_atividades_tb_t_idx` (`tb_temperatura_id_temperatura` ASC),
  CONSTRAINT `fk_tb_historico_atividades_has_tb_historico_atividades_tb_his1`
    FOREIGN KEY (`tb_historico_atividades_id_atividades`)
    REFERENCES `RP_bd`.`tb_mudanca_climatica` (`id_atividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_historico_atividades_has_tb_historico_atividades_tb_tem1`
    FOREIGN KEY (`tb_temperatura_id_temperatura`)
    REFERENCES `RP_bd`.`tb_temperatura` (`id_temperatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_coleta_dados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_coleta_dados` (
  `idcoleta` INT NOT NULL,
  `tb_temperatura_id_temperatura` INT NOT NULL,
  `tb_umidade_ar_id_umidade_ar` INT NOT NULL,
  `tb_umidade_solo_id_umidade_solo` INT NOT NULL,
  `tb_Planta_id_Planta` INT NOT NULL,
  PRIMARY KEY (`idcoleta`),
  INDEX `fk_coleta_tb_temperatura1_idx` (`tb_temperatura_id_temperatura` ASC),
  INDEX `fk_coleta_tb_umidade_ar1_idx` (`tb_umidade_ar_id_umidade_ar` ASC),
  INDEX `fk_coleta_tb_umidade_solo1_idx` (`tb_umidade_solo_id_umidade_solo` ASC),
  INDEX `fk_coleta_tb_Planta1_idx` (`tb_Planta_id_Planta` ASC),
  CONSTRAINT `fk_coleta_tb_temperatura1`
    FOREIGN KEY (`tb_temperatura_id_temperatura`)
    REFERENCES `RP_bd`.`tb_temperatura` (`id_temperatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleta_tb_umidade_ar1`
    FOREIGN KEY (`tb_umidade_ar_id_umidade_ar`)
    REFERENCES `RP_bd`.`tb_umidade_ar` (`id_umidade_ar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleta_tb_umidade_solo1`
    FOREIGN KEY (`tb_umidade_solo_id_umidade_solo`)
    REFERENCES `RP_bd`.`tb_umidade_solo` (`id_umidade_solo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleta_tb_Planta1`
    FOREIGN KEY (`tb_Planta_id_Planta`)
    REFERENCES `RP_bd`.`tb_Planta` (`id_Planta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
