-- MySQL Script generated by MySQL Workbench
-- Mon Aug 21 15:58:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RP_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RP_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RP_bd` DEFAULT CHARACTER SET utf8 ;
USE `RP_bd` ;

-- -----------------------------------------------------
-- Table `RP_bd`.`tb_Planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_Planta` (
  `id_Planta` INT NOT NULL AUTO_INCREMENT,
  `tipo_ amostra` VARCHAR(45) NOT NULL,
  `dt_plantacao` DATE NOT NULL,
  PRIMARY KEY (`id_Planta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_plantacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_plantacao` (
  `id_plantacao` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_plantacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_temperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_temperatura` (
  `id_temperatura` INT NOT NULL AUTO_INCREMENT,
  `temperatura` DOUBLE NOT NULL,
  `hora_amostra` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id_temperatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_umidade_solo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_umidade_solo` (
  `id_umidade_solo` INT NOT NULL AUTO_INCREMENT,
  `umidade` DOUBLE NOT NULL,
  `hora_amostra` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id_umidade_solo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_umidade_ar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_umidade_ar` (
  `id_umidade_ar` INT NOT NULL AUTO_INCREMENT,
  `umidade` DOUBLE NOT NULL,
  `hora_amostra` DOUBLE NOT NULL,
  PRIMARY KEY (`id_umidade_ar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`media_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`media_dia` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`atividade` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_consumo_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_consumo_diario` (
  `id_consumo_diario` INT NOT NULL AUTO_INCREMENT,
  `qt_agua` DOUBLE NOT NULL,
  `qt_energia` DOUBLE NOT NULL,
  `qt_luminosidade` DOUBLE NOT NULL,
  PRIMARY KEY (`id_consumo_diario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_energia_armazenada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_energia_armazenada` (
  `id_energia_armazenada` INT NOT NULL AUTO_INCREMENT,
  `qt_energia` DOUBLE NOT NULL,
  PRIMARY KEY (`id_energia_armazenada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RP_bd`.`tb_health`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RP_bd`.`tb_health` (
  `id_health` INT NOT NULL,
  PRIMARY KEY (`id_health`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
